# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 81ec4eee83ed0e5b60fad9448c3d3875a51a3ccdd2518bca8451ed6998e3a3c9b51e17596c9278ea5939602bed5cd36f705cfb026f36715effa27b747293866e

test:
  secret_key_base: 7b23a651c736cd630b4d44899dcaedb7f661320960bf5b7b77e5fa63348b371a1e4943f2bbf7af7ab691e01d9f766fdfb938c5a4a1741bc2e65213fd7dbe389a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
